version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
    rust: "1.86"

sphinx:
  configuration: rapidgeo-py/docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: rapidgeo-py/docs/requirements.txt
    - method: pip
      path: rapidgeo-py
      extra_requirements:
        - numpy
